### ISSUE TITLE
ReferenceError window is not defined.

### ISSUE THREAD

**Issue by DevChristians** [creativetimofficial/vuetify-material-dashboard#17]
Hello! colleagues I have a problem. I am installing this theme for my dashboard https://demos.creative-tim.com/vue-material-dashboard/?_ga=2.87424920.1430341878.1550962222-1433739867.1550437929#/dashboard ok. But importing the **vue-chartist** plugin I have an error and it is not precisely in the vue-chartist package but the main **chartist** package, the error is appended.

1. > Error 
![image](https://user-images.githubusercontent.com/27924062/53301574-d8e24480-382a-11e9-8809-24c86be74a6e.png)

2. > my file nuxt.config.js
![image](https://user-images.githubusercontent.com/27924062/53301679-3f1b9700-382c-11e9-892c-e4bbddd322ac.png)

3. > my plugins structure
![image](https://user-images.githubusercontent.com/27924062/53301684-58244800-382c-11e9-8f27-ca56202b6e3b.png)

4. > my plugins file index
![image](https://user-images.githubusercontent.com/27924062/53301706-8b66d700-382c-11e9-81d9-74ac27b707e8.png)

5. >my chartist.js file
![image](https://user-images.githubusercontent.com/27924062/53301720-c49f4700-382c-11e9-8fff-a268a1332bbb.png)

I would like to hear suggestions to solve this, I thank you very much!
Greetings.

**Comment by dragosct10** [comment]
Hi, @DevChristians! Thank you for using our products. I found in their repo an issue who seems to be similar yours, please look at this [link](https://github.com/Yopadd/vue-chartist/issues/2). 

Regards, 
Dragos
