### ISSUE TITLE
how to add custom view like login page ?

### ISSUE THREAD

**Issue by tarikhagustia** [creativetimofficial/vuetify-material-dashboard#19]
hi, how to add custom view without inherit to admin page ?

**Comment by dragosct10** [comment]
Hi, @tarikhagustia! Thank you for using our products. Please, can you be more explicit? 

Regards, 
Dragos

**Comment by kinow** [comment]
@tarikhagustia we added one without much effort, just found [an example from Vuetify](https://vuetifyjs.com/en/examples/layouts/centered) and modified a bit for [what we needed](https://github.com/cylc/cylc-web/blob/master/src/views/Login.vue).

**Comment by tarikhagustia** [comment]
hi @dragosct10 thanks for replaying, what i want is to add new page without using admin template,

**Comment by dragosct10** [comment]
Hi! I understand now that you want a page with another layout and this will be available in the PRO version, but you can try to see [this](https://levelup.gitconnected.com/multiple-layouts-for-vue-spa-app-fafda6b2bfc7) and here you will find information on how to use multiple views. 

Regards, 
Dragos

**Comment by micklynch** [comment]
Another option is to hide parts of the layout, like certain buttons on the tool bar and certain links on the Drawer when `!isLoggedIn()`

The function could get the login status from Vuex using a getter.

**Comment by tarikhagustia** [comment]
thanks @dragosct10 and @micklynch i will try @micklynch solution .. i'll close this issue
