### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by BarGo94** [creativetimofficial/vuetify-material-dashboard#2]
Hi ,
thank you for this product but i have some question , i'm a new developer of VueJS and there are so many template to create project,  but i want to use your's and for this i want to ask if it's possible and how to add the pwa feature and the service worker to this template ? 
(In other projects,there are other folders as build and config to add configuration of pwa and the service worker) . 

Thanks for replying.

**Comment by MrJmpl3** [comment]
PWA is independent of the template, you can do PWA any template, with the knowledge of the Service Workers

**Comment by johnleider** [comment]
Here is information regarding using PWA with Vue CLI: https://cli.vuejs.org/core-plugins/pwa.html
