### ISSUE TITLE
[Feature Request] Can't install vuetify-material-dashboard on existing project

### ISSUE THREAD

**Issue by RatarovDaniil** [creativetimofficial/vuetify-material-dashboard#32]
### What is your enhancement?
Hi,
I don't understand and did not find any information about how I can import specific components or whole framework on my already existing project. In all manuals it's been said that you can download our repo and run 'npm install'. I tried 'npm install --save vuetify-material-dashboard' and it has installed it in node_modules folder, so what should I type afterwards to be able to use components? Also, when I try to add something like "import VuetifyMaterialDashboard from 'vuetify-material-dashboard'" to main.js it complains that 'vuetify-material-dashboard' not installed... Can you please give me a glimpse on how it should work?

**Comment by dragosct10** [comment]
Hi, @RatarovDaniil! Thank you for using our products. Unfortunately, you can't import the components from npm, you can just take them manually. We work on this to have the components separately to have the option to import them. 

Regards,
Dragos

**Comment by RatarovDaniil** [comment]
Hi @dragosct10, got it, thank you!
Best regards,
Daniil
