### ISSUE TITLE
Please , don't commit in master

### ISSUE THREAD

**Issue by MrJmpl3** [creativetimofficial/vuetify-material-dashboard#36]
Please, don't commit in master to testing. Is some confuse.

Make a branch and merge.

In other words, I work upgrade this version to Vuetify 2.0 

https://github.com/MrJmpl3/vuetify-material-dashboard/tree/vuetify-2.0-and-other-things

**Comment by dragosct10** [comment]
Hi, @MrJmpl3! We just updated the product to v2.0.0. 

Regards,
Dragos

**Comment by MrJmpl3** [comment]
@dragosct10 A question, for the new version, you use Vuetify Loader or CSS generated? .. I think create a pull request
