### ISSUE TITLE
Vuetify datepicker - blank fields

### ISSUE THREAD

**Issue by nunopeixoto** [creativetimofficial/vuetify-material-dashboard#7]
Hello everyone. 
I'm just trying to add a simple vuetify date picker (the dialog one), and when I try to do so, the date picker works but the styling appears a bit awkward as you can see in the image below.
When I click the dates on the date picker they are selected as they should to the v-textfield. 
The code is exactly the same as Vuetify documentation suggests, I actually had it working before changing to this template. 

There is no error's on console.

![image](https://user-images.githubusercontent.com/44769043/50830076-8d3d0f80-133e-11e9-8d22-87de994d4347.png)

**Comment by nunopeixoto** [comment]
With help of some other guy with the same mistake I have it solved. Just remove the !important from the _buttons.scss (v-btn class, color property).

**Comment by daskyrk** [comment]
@nunopeixoto how do you solve the padding & margin problem? I found the theme also affected the date picker container border-radius by `.v-menu__content` from `_fixed-plugin.scss`.

**Comment by nunopeixoto** [comment]
Removing the !important solved all my problems.

**Comment by ArthurConceicao** [comment]
Add padding 0 to ".v-date-picker-table .v-btn"
