### ISSUE TITLE
Navigation drawer is not scroll-able

### ISSUE THREAD

**Issue by AmirrezaNasiri** [creativetimofficial/vuetify-material-dashboard#8]
First of all, thank you for this great dashboard.  

**What is the problem?**
`core-drawer`'s navigation list is not scroll-able thus if we add few more links to `links` prop, only some of them that fit the screen (as high as highest main/router component) will be visible.  
I tried to add `overflow-y: scroll;` but I got no luck. Can you please explain us how to fix it?

**What is expected?**   
The navigation bar is expected to work like [Vue Light Bootstrap Dashboard](https://demos.creative-tim.com/vue-light-bootstrap-dashboard/#/admin/overview):
![expected](https://user-images.githubusercontent.com/19557224/51413150-2102ad00-1b83-11e9-8f8c-020dabc13fbe.gif)

As you can see, we can scroll navigation section and see other items which don't fit in current screen.

**What is happening?**
Currently we can only see items which are fit in the screen's height and nothing more. The problem is happening because this section is not scroll-able:
![what-is-happening](https://user-images.githubusercontent.com/19557224/51413678-f3b6fe80-1b84-11e9-97b9-fa189340752a.gif)

**How to reproduce it?**
Simply expand `links` prop in `src/components/core/Drawer.vue` to contain more links. Something like this:
```
links: [
      {
        to  : '/dashboard',
        icon: 'mdi-folder-plus',
        text: 'Dashboard',
      },
      {
        to  : '/user-profile',
        icon: 'mdi-account',
        text: 'User Profile',
      },
      {
        to  : '/typography',
        icon: 'mdi-format-font',
        text: 'Typography',
      },
      {
        to  : '/icons',
        icon: 'mdi-chart-bubble',
        text: 'Icons',
      },
      {
        to  : '/maps',
        icon: 'mdi-map-marker',
        text: 'Maps',
      },
      {
        to  : '/notifications',
        icon: 'mdi-bell',
        text: 'Notifications',
      },
      {
        to  : '/notifications',
        icon: 'mdi-bell',
        text: 'Just making list bigger',
      },
      {
        to  : '/notifications',
        icon: 'mdi-bell',
        text: 'And more bigger',
      },
      {
        to  : '/notifications',
        icon: 'mdi-bell',
        text: 'Can you see me?',
      },
      {
        to  : '/notifications',
        icon: 'mdi-bell',
        text: 'I may not fit in your screen',
      },
      {
        to  : '/notifications',
        icon: 'mdi-bell',
       text: 'No way you can see me!',
      },
      {
        to  : '/notifications',
        icon: 'mdi-bell',
        text: 'This is the greatest place to hide a corpse :))',
      },
]
```

Well, can you see the item which hides the corpse?

**Is problem related to me only?**   
No. You can see the [original demo](https://demos.creative-tim.com/vuetify-material-dashboard/#/dashboard) which is alive. Try to open it in some short-height screens and you can see that you have no access to some of the items.

**What about the solution?**
Adding `overflow-y: auto` to `.v-responsive__content` will fix it but I didn't send a pull request since the way I did this wasn't clean enough!

**Comment by dragosct10** [comment]
Hi, @AmirrezaNasiri! Thank you for using our products. Please, can you give us your link to see what it's happening there? 

Regards,
Dragos

**Comment by CumpsD** [comment]
@AmirrezaNasiri did you find a solution for this?

**Comment by jiahong96** [comment]
any solution?

**Comment by AmirrezaNasiri** [comment]
@jiahong96 @CumpsD 
I've created a pull request for this issue. Till it's being reviewed/merged, you can see [changes ](https://github.com/creativetimofficial/vuetify-material-dashboard/pull/21/files) to resolve the issue.

**Comment by MrJmpl3** [comment]
Use Perfect Scrollbar , is smooth and simple , and add CSS: 

```css
position: relative;
height: calc(100vh - $height-sidebar);
overflow: auto;
```
