### ISSUE TITLE
no Login

### ISSUE THREAD

**Issue by diaolingzc** [creativetimofficial/vuetify-material-dashboard#9]
App.vue
```
  <v-app>
    <core-filter />

    <core-toolbar />

    <core-drawer />

    <core-view />
  </v-app>
```
View.vue
```
<template>
  <v-content>
    <div id="core-view">
      <v-fade-transition mode="out-in">
        <router-view />
      </v-fade-transition>
    </div>
    <core-footer v-if="$route.name !== 'Maps'" />
  </v-content>
</template>
```

这样使用router-view  集成login是一件很难的事。

**Comment by CiaranPearse** [comment]
you'll need to roll your own for that.

**Comment by micklynch** [comment]
Here is a [nice tutorial](https://scotch.io/tutorials/handling-authentication-in-vue-using-vuex) of how to do it yourself.

**Comment by ClintOxx** [comment]
@diaolingzc i added login and other stuff to this template here https://github.com/ClintOxx/vuetify-admin-dashboard

**Comment by johnleider** [comment]
Closing as resolved.
